import type { BusanRewindData } from "./types";

export const SAMPLE_INDUSTRY_CODE = "28";

export const sampleBusanRewindData: BusanRewindData = {
  aiReviewBriefing: {
    briefingMarkdown:
      "## 현재 산업 현황\n\n- **전기장비 제조업**은 생산 자동화와 에너지 전환 수요를 함께 받는 산업으로 검토할 필요가 있습니다. [스마트 제조 투자 확대](https://news.google.com/search?q=%EC%8A%A4%EB%A7%88%ED%8A%B8%20%EC%A0%9C%EC%A1%B0%20%ED%88%AC%EC%9E%90)\n- 현재 산업 현황에서는 종사자 증가 흐름과 디지털 전환 키워드가 함께 확인되므로, 단순 성장률보다 실행 역량을 같이 봐야 합니다.\n\n## 과거 유사 사례\n\n- 과거 유사 시기에는 스마트공장 구축과 제조 데이터 활용 지원이 중심이었습니다.\n- 현재 지원사업은 **AI·AX 기술 도입**, **ESG·탄소중립**, **디지털 전환 컨설팅**처럼 기술 전환 관점이 강화되었습니다.\n\n## 지원사업 검토 관점\n\n- 기업 검토 시에는 매출 증가 여부와 산업 전체 회복 흐름을 비교해 기업 고유 변화인지 확인할 수 있습니다.\n- 고용 변화는 수요 확대 국면에서 생산 대응 가능성을 판단하는 보조 지표로 활용할 수 있습니다. [제조 인력 수요 변화](https://news.google.com/search?q=%EC%A0%9C%EC%A1%B0%EC%97%85%20%EC%9D%B8%EB%A0%A5%20%EC%88%98%EC%9A%94)\n\n## 검토 포인트\n\n- 기업별 **매출액, 영업이익률, 부채비율, 자산/부채/자본**을 함께 확인해 성장성과 재무 부담을 같이 검토할 필요가 있습니다.\n- 수요 확대 산업에서는 **종사자수 변화, R&D 비용, 특허·인증, 연구·활동, 디지털 전환 근거**를 함께 보면 실행 역량을 판단하는 데 도움이 됩니다.\n- 과거 지원사업과 **중복지원 이력**은 동일 목적의 반복 지원인지, 단계적 고도화인지 구분하는 참고 지표로 활용할 수 있습니다.\n\n## 참고 근거와 한계\n\n- 본 내용은 산업 동향과 과거 지원 이력을 종합한 참고자료이며, 지원 여부를 판단하거나 평가 결과를 제시하지 않습니다.",
    briefingLines: [
      "전기장비 제조업은 생산 자동화와 에너지 전환 수요를 함께 받는 산업으로 검토할 필요가 있습니다. [스마트 제조 투자 확대](https://news.google.com/search?q=%EC%8A%A4%EB%A7%88%ED%8A%B8%20%EC%A0%9C%EC%A1%B0%20%ED%88%AC%EC%9E%90)",
      "현재 산업 현황에서는 종사자 증가 흐름과 디지털 전환 키워드가 함께 확인되므로, 단순 성장률보다 실행 역량을 같이 봐야 합니다.",
      "과거 유사 시기에는 스마트공장 구축과 제조 데이터 활용 지원이 중심이었습니다.",
      "현재 지원사업은 AI·AX 기술 도입, ESG·탄소중립, 디지털 전환 컨설팅처럼 기술 전환 관점이 강화되었습니다.",
      "기업 검토 시에는 매출 증가 여부와 산업 전체 회복 흐름을 비교해 기업 고유 변화인지 확인할 수 있습니다.",
      "고용 변화는 수요 확대 국면에서 생산 대응 가능성을 판단하는 보조 지표로 활용할 수 있습니다. [제조 인력 수요 변화](https://news.google.com/search?q=%EC%A0%9C%EC%A1%B0%EC%97%85%20%EC%9D%B8%EB%A0%A5%20%EC%88%98%EC%9A%94)",
      "과거 지원 방향과 현재 지원 목적의 차이를 같이 보면 현재 사업의 추진 배경을 이해하는 데 도움이 됩니다.",
      "본 내용은 산업 동향과 과거 지원 이력을 종합한 참고자료이며, 지원 여부를 판단하거나 평가 결과를 제시하지 않습니다.",
    ],
    evidenceNews: [
      {
        industryChange: "디지털 전환 확대",
        link: "https://news.google.com/search?q=%EC%8A%A4%EB%A7%88%ED%8A%B8%20%EC%A0%9C%EC%A1%B0%20%ED%88%AC%EC%9E%90",
        publishedAt: "2026.07.18",
        source: "Google News RSS",
        title: "AI 기반 스마트공장 구축 투자 확대",
      },
      {
        industryChange: "인력·고용 여건 변화",
        link: "https://news.google.com/search?q=%EC%A0%9C%EC%A1%B0%EC%97%85%20%EC%9D%B8%EB%A0%A5%20%EC%88%98%EC%9A%94",
        publishedAt: "2026.07.10",
        source: "Google News RSS",
        title: "제조업 인력 수요 증가와 생산 대응 과제",
      },
    ],
    industryCode: SAMPLE_INDUSTRY_CODE,
    industryName: "전기장비 제조업",
    newsSynthesis:
      "최근 RSS 기사에서는 디지털 전환 투자와 인력 수요 변화가 함께 확인됩니다. 산업 수요가 확대되는 경우에도 생산 여건이 제한될 수 있으므로, 기업 검토 시 재무지표와 고용 역량을 함께 확인할 수 있습니다.",
    source: "RULE_BASED_RSS",
    title: "AI 종합 검토 브리핑",
  },
  currentStatus: {
    baseYear: 2025,
    corporation: { count: 7834, ratio: 76.2 },
    districtEmployeeGrowths: [
      { districtName: "해운대구", growthRate: 15.8, sggCode: "26350" },
      { districtName: "강서구", growthRate: -4.2, sggCode: "26440" },
      { districtName: "금정구", growthRate: 8.4, sggCode: "26410" },
      { districtName: "사상구", growthRate: -7.1, sggCode: "26530" },
    ],
    employeeCount: 10152,
    employeeGrowthRate: 8.7,
    employeeSizeRatios: [
      { label: "300인 이상", ratio: 13.2 },
      { label: "50~299인", ratio: 28.7 },
      { label: "5~49인", ratio: 36.8 },
      { label: "5인 미만", ratio: 21.3 },
    ],
    individual: { count: 2318, ratio: 23.8 },
    industryCode: SAMPLE_INDUSTRY_CODE,
    industryName: "전기장비 제조업",
    previousYear: 2024,
  },
  currentSupportPrograms: {
    industryCode: SAMPLE_INDUSTRY_CODE,
    referenceYear: 2026,
    items: [
      {
        announceUrl: "https://www.btp.or.kr",
        dueDate: "2026-06-20",
        programId: 101,
        referenceYear: 2026,
        status: "접수중",
        summary: "스마트공장 구축 및 고도화 지원",
        supportField: "스마트공장",
        title: "2026 스마트제조혁신 기술지원사업",
      },
      {
        announceUrl: "https://www.btp.or.kr",
        dueDate: "2026-07-15",
        programId: 102,
        referenceYear: 2026,
        status: "접수중",
        summary: "스마트 장비 도입 및 운영 최적화를 위한 컨설팅과 일부 구축비를 지원합니다.",
        supportField: "AI·AX",
        title: "AI·데이터 기반 제조혁신 지원사업",
      },
      {
        announceUrl: null,
        dueDate: "2026-07-20",
        programId: 103,
        referenceYear: 2026,
        status: "예정",
        summary: "친환경 공정 전환과 탄소 저감 설비 검토를 위한 진단 및 고도화 계획 수립을 지원합니다.",
        supportField: "ESG·탄소중립",
        title: "친환경 제조공정 전환 지원사업",
      },
    ],
  },
  trendBriefing: {
    aiSummary: "스마트 제조 산업은 국내에서 디지털 전환과 AI 자동화 도입이 확산되고 있으며, 부산 제조 기반과 연관성이 높습니다.",
    busanRelevance: {
      policyKeywords: ["탄소중립", "AX/DX", "ESG", "지역 고용"],
      strategicIndustries: ["스마트제조", "첨단기계"],
    },
    changeComparison: {
      demand: "자동차·전자·조선 수요 확대",
      product: "제품·자동화·지능형 제품 비중 증가",
      structure: "자동화·디지털화 중심 재편",
      technology: "데이터·AI 기반 공정 기술 확대",
    },
    domestic: {
      growthRate: 3.1,
      issues: ["한국은행 업종 성장률 상승", "최근 3~5년 성장 추이 개선"],
    },
    growthSeries: [
      { growthRate: 3.0, year: 2021 },
      { growthRate: 2.1, year: 2022 },
      { growthRate: -0.4, year: 2023 },
      { growthRate: 1.8, year: 2024 },
      { growthRate: 3.1, year: 2025 },
    ],
    industryCode: SAMPLE_INDUSTRY_CODE,
    industryName: "전기장비 제조업",
    overseas: {
      issues: ["친환경 제조기반 AI 자동화 투자 증가", "탄소중립 대응을 위한 스마트 제조 전환 가속"],
    },
    summarySource: "RULE_BASED",
  },
  similarFlow: {
    flowType: "최근 급상승",
    industryCode: SAMPLE_INDUSTRY_CODE,
    matchedPeriod: { endYear: 2016, label: "2013~2016", startYear: 2013 },
    periodHighlights: [
      { changeRate: -18.4, endYear: 2016, label: "하락기", startYear: 2013 },
      { changeRate: 32.6, endYear: 2021, label: "회복·상승기", startYear: 2017 },
      { changeRate: 28.7, endYear: 2025, label: "최근", startYear: 2022 },
    ],
    series: [
      { index: 100, year: 2012 },
      { index: 112, year: 2013 },
      { index: 101, year: 2014 },
      { index: 92, year: 2015 },
      { index: 86, year: 2016 },
      { index: 116, year: 2022 },
      { index: 124, year: 2023 },
      { index: 130, year: 2024 },
      { index: 130, year: 2025 },
    ],
    summary: "2022년 이후 빠르게 상승하고 있는 최근 급상승 유형입니다.",
  },
  pastSupportReview: {
    industryChangeSummary: "2013~2017년에는 종사자 규모와 산업 분포가 축소되는 흐름이 확인되었고, 2018년 이후 스마트공정 및 제조 데이터 활용 관련 지원사업이 함께 확인됩니다.",
    industryChanges: [
      { changeRate: 32.6, label: "종사자 규모 변화" },
      { changeRate: 12.4, label: "개인/법인 비중 변화" },
      { changeRate: 8.7, label: "지역별 산업 분포 변화" },
    ],
    industryCode: SAMPLE_INDUSTRY_CODE,
    matchedPeriod: { endYear: 2017, label: "2013~2017", startYear: 2013 },
    pastSupportPrograms: [
      {
        programId: 2016,
        purpose: "제조 현장 자동화 기반 마련",
        supportAmountThousandKrw: 2000000,
        supportContent: "설비 구축 및 공정 개선",
        supportField: "스마트공장 구축",
        target: "부산 소재 중소 제조기업",
        title: "스마트공정 기초 구축 지원사업",
        year: 2016,
      },
      {
        programId: 2018,
        purpose: "데이터 수집·분석 기반 운영 효율화",
        supportAmountThousandKrw: 1500000,
        supportContent: "데이터·IoT 도입",
        supportField: "데이터 활용",
        target: "부산 소재 중소 제조기업",
        title: "제조 데이터 활용 지원사업",
        year: 2018,
      },
      {
        programId: 2020,
        purpose: "스마트공장 고도화 및 확산",
        supportAmountThousandKrw: 2500000,
        supportContent: "자동화·AI",
        supportField: "스마트제조 고도화",
        target: "부산 소재 중소 제조기업",
        title: "스마트제조 고도화 지원사업",
        year: 2020,
      },
    ],
    supportedCompanyChanges: [
      {
        activityChange: "생산라인 자동화 구축",
        companyId: 1,
        companyName: "A 기업",
        employeeAfter: 68,
        employeeBefore: 45,
        rndChange: "품질 자동화 알고리즘 개발",
        salesAfterAmount: 5800000000,
        salesBeforeAmount: 3200000000,
        supportYear: 2018,
      },
      {
        activityChange: "스마트팩토리 구축 완료",
        companyId: 2,
        companyName: "B 기업",
        employeeAfter: 46,
        employeeBefore: 30,
        rndChange: "AI 기반 물류 예측 시스템 개발",
        salesAfterAmount: 3900000000,
        salesBeforeAmount: 2100000000,
        supportYear: 2020,
      },
      {
        activityChange: "데이터 기반 생산관리 도입",
        companyId: 3,
        companyName: "C 기업",
        employeeAfter: 41,
        employeeBefore: 28,
        rndChange: "IoT 센서 데이터 분석 고도화",
        salesAfterAmount: 3300000000,
        salesBeforeAmount: 1800000000,
        supportYear: 2019,
      },
    ],
  },
  supportComparison: {
    aiSummary: "과거 지원사업은 스마트공장 구축과 제조 데이터 활용 중심이었고, 현재는 AI·AX 기술 도입과 ESG·탄소중립 대응이 새롭게 강조됩니다.",
    changedFields: [{ from: "단순 자동화 설비 중심", to: "AI·데이터 기반 제조 혁신 중심" }],
    commonFields: ["스마트공장 구축", "제조 데이터 활용", "공정 자동화", "인력 양성"],
    currentFields: ["AI·AX 기술 도입 지원", "ESG·탄소중립 대응 지원", "디지털 전환 컨설팅"],
    industryCode: SAMPLE_INDUSTRY_CODE,
    newFields: ["AI 사전 수요", "ESG·탄소공정 대응 지원", "대기업 협업 컨설팅"],
    pastFields: ["스마트공장 구축", "제조 데이터 활용", "공정 자동화", "인력 양성", "기술 컨설팅"],
    referenceYear: 2026,
    trendKeywords: ["AI/AX", "스마트 제조", "데이터 활용", "ESG", "탄소중립", "지역 고용"],
  },
};
